# Generated by Django 3.0.5 on 2021-07-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
